import './styles/global.scss'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
    subsets: ["latin-ext"],
    weight: ["300", "400", "500"],
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={poppins.className}>{children}</body>
        </html>
    )
}
